export const NOTIFICATION = {
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
  INFO: 'INFO',
};

export const SUCCESS = {
  LOGGED_IN: 'LOGGED_IN',
  REGISTRATION: 'REGISTRATION',
  USER_EDITION: 'USER_EDITION',
  USER_JOB_EDITION: 'USER_JOB_EDITION',
  USER_JOB_ADD: 'USER_JOB_ADD',
  USER_JOB_DELETE: 'USER_JOB_DELETE',
  PASSWORD_RESET: 'PASSWORD_RESET',
};

export const WARNING = {};

export const ERROR = {
  NO_ACTIVE_ACCOUNT: 'NO_ACTIVE_ACCOUNT',
  NO_STUDENT: 'NO_STUDENT',
  STUDENT_NOT_AVAILABLE: 'STUDENT_NOT_AVAILABLE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  NOT_FOUND: 'NOT_FOUND',
};

export const INFO = {
  SIGN_OUT: 'SIGN_OUT',
};
